

import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://192.168.20.26:82/peza-ed/login")
    page.get_by_role("textbox", name="Username").click()
    page.get_by_role("textbox", name="Username").fill("Applicant")
    page.get_by_role("textbox", name="Username").dblclick()
    page.get_by_role("textbox", name="Username").fill("cgbc")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("Peza_123")
    page.get_by_role("button", name="Sign in").click()


    page.get_by_role("link", name=" Applications & Accreditations").click()
    page.get_by_role("button", name="+ New Ecozone Enterprise").click()
    page.locator("#undertakingsModal div").filter(has_text="I Agree").nth(3).click()
    page.get_by_role("checkbox", name="I Agree").check()
    page.locator("#btnSubmitUndertaking").click()
    page.get_by_text("Domestic Market").click()
    page.get_by_role("textbox", name="Select Section Code").click()
    page.get_by_role("option", name="Accommodation and Food").click()
    page.get_by_role("textbox", name="Select Division Code").click()
    page.get_by_role("option", name="[55] ACCOMMODATION").click()
    page.get_by_role("textbox", name="[55] ACCOMMODATION").click()
    page.get_by_role("option", name="[56] FOOD AND BEVERAGE").click()
    page.locator("#select2-groupCodeId-container").click()
    page.locator("#select2-groupCodeId-container").click()
    page.locator("#select2-groupCodeId-container").click()
    page.locator("#select2-groupCodeId-container").click()
    page.locator("#select2-groupCodeId-container").click()
    page.get_by_role("option", name="[561] Restaurants and mobile").click()
    page.get_by_role("textbox", name="[561] Restaurants and mobile").click()
    page.get_by_role("option", name="[562] Event catering and").click()
    page.get_by_role("textbox", name="[562] Event catering and").click()
    page.get_by_role("option", name="[563] Beverage serving").click()
    page.get_by_role("textbox", name="Select Classes Code").click()
    page.get_by_role("option", name="[5630] Beverage serving").click()
    page.get_by_role("textbox", name="Select Sub-classes Code").click()
    page.get_by_role("option", name="[56301] Night clubs").click()
    page.get_by_role("textbox", name="[56301] Night clubs").click()
    page.get_by_role("option", name="[56302] Bars and cocktail").click()
    page.get_by_role("textbox", name="[56302] Bars and cocktail").click()
    page.get_by_role("option", name="[56303] Café or coffee shops").click()
    page.get_by_role("option", name="[56304] Tea shops").click()
    page.get_by_role("option", name="[56304] Tea shops").click()
    page.get_by_role("textbox", name="[56304] Tea shops").click()
    page.get_by_role("option", name="[56309] Other beverage").click()
    page.get_by_role("textbox", name="[56309] Other beverage").click()
    page.get_by_text("* Application Fill up all the required fields of information below *VASP: CDEC").click()
    page.get_by_role("button", name="Proceed").click()
    page.get_by_role("textbox", name="Company Name").click()
    page.get_by_role("textbox", name="Company Name").click()
    page.get_by_role("textbox", name="Company Name").press("CapsLock")
    page.get_by_role("textbox", name="Company Name").fill("COMPANY NAME")
    page.get_by_role("textbox", name="Company Name").click(button="right")
    page.get_by_role("textbox", name="Company Name").click()
    page.get_by_role("textbox", name="Company Name").click()
    page.get_by_role("textbox", name="Company Name").click(button="right")
    page.get_by_role("textbox", name="Company Name").click()
    expect(page.get_by_role("textbox", name="Company Name")).to_be_visible()
    page.get_by_role("textbox", name="Select Country").click()
    expect(page.get_by_role("textbox", name="Select Country")).to_be_visible()
    page.get_by_role("textbox", name="Nature of Business").click()
    expect(page.get_by_role("textbox", name="* Company Profile:")).to_be_visible()
    expect(page.get_by_role("textbox", name="* Company Profile:")).to_be_visible()
    page.get_by_role("textbox", name="* Company Profile:").click()
    expect(page.get_by_role("textbox", name="* First Name:")).to_be_visible()
    expect(page.get_by_role("textbox", name="METRO MANILA")).to_be_visible()
    expect(page.get_by_role("textbox", name="TAGUIG CITY")).to_be_visible()
    expect(page.get_by_role("textbox", name="FORT BONIFACIO")).to_be_visible()
    expect(page.get_by_role("textbox", name="Street Name")).to_be_visible()
    expect(page.get_by_role("textbox", name="Landline no.:")).to_be_visible()
    expect(page.get_by_role("textbox", name="* Email Address:")).to_be_visible()
    expect(page.get_by_role("textbox", name="Website: (Optional)")).to_be_visible()
    page.get_by_role("textbox", name="Company Name").click()
    page.get_by_role("textbox", name="Company Name").fill("COMPANY NAME TESTING 001")
    page.get_by_role("textbox", name="Nature of Business").click()
    page.get_by_role("textbox", name="Nature of Business").fill("NATURE OF BUSINESS TESTING 001")
    page.get_by_role("textbox", name="* Company Profile:").click()
    page.get_by_role("textbox", name="* Company Profile:").fill("COMPANY PROFILE TESTING 001")
    page.get_by_role("textbox", name="* Company Profile:").click()
    page.get_by_role("textbox", name="* Company Profile:").fill("COMPANY PROFILE TESTING 001 TESTING TESTING")
    page.get_by_role("button", name="Save and Proceed").click()
    expect(page.get_by_role("textbox", name="SELECT PROPOSED PRODUCT/")).to_be_visible()
    page.get_by_role("textbox", name="* Description:").click()
    expect(page.get_by_role("textbox", name="* Description:")).to_be_visible()
    expect(page.get_by_role("textbox", name="* Uses/Application:")).to_be_visible()
    expect(page.locator("#activity_product_img_documentsDropzone")).to_be_visible()
    expect(page.get_by_role("button", name="Save and Proceed")).to_be_visible()
    page.get_by_role("textbox", name="SELECT PROPOSED PRODUCT/").click()
    page.get_by_role("textbox", name="SELECT PROPOSED PRODUCT/").click()
    page.get_by_role("button", name="+").click()
    page.locator("#newBusinessProductActivity").click()
    page.locator("#newBusinessProductActivity").press("CapsLock")
    page.locator("#newBusinessProductActivity").fill("N")
    page.locator("#newBusinessProductActivity").press("CapsLock")
    page.locator("#newBusinessProductActivity").fill("NEW PROPOSES PRODUCT ACTIVITY 001")
    page.get_by_role("button", name=" Add").click()
    page.get_by_role("textbox", name="* Description:").click()
    page.get_by_role("textbox", name="* Description:").fill("NEW PROPOSE PRODUCT ACTIVITY 001 DESCRIPTION")
    page.get_by_role("textbox", name="* Uses/Application:").click()
    page.get_by_role("textbox", name="* Uses/Application:").fill("NEW PRODUCT USES AND APPLICATION 0001")
    page.get_by_text("choose a file").click()
    page.get_by_text("Loading... Dashboard Permit").set_input_files("Testing_document.png")
    page.locator("#activity_product_img_documentsDropzone div").click()
    page.get_by_text("Loading... Dashboard Permit").set_input_files("NSW Schedule.pdf")
    page.get_by_role("button", name="Save and Proceed").click()
    expect(page.get_by_role("row", name="Securities & Exchange").get_by_placeholder("DD-MMM-YYYY")).to_be_visible()
    expect(page.locator("input[name=\"businessRegInfoAppsBean[0].reg_no\"]")).to_be_visible()
    expect(page.get_by_role("textbox", name="Sec Primary Purpose")).to_be_visible()
    expect(page.get_by_role("textbox", name="Authorized Amount (PHP)")).to_be_visible()
    expect(page.get_by_role("textbox", name="Subscribe Amount (PHP)")).to_be_visible()
    expect(page.get_by_role("textbox", name="* Paid-up Amount (PHP):")).to_be_visible()
    expect(page.get_by_role("textbox", name="* Paid-up Amount (PHP):")).to_be_visible()
    expect(page.get_by_role("button", name="Save and Proceed")).to_be_visible()
    page.get_by_role("row", name="Securities & Exchange").get_by_role("cell").nth(1).click()
    page.get_by_role("row", name="Securities & Exchange").get_by_placeholder("DD-MMM-YYYY").fill("2025-07-29")
    page.locator("input[name=\"businessRegInfoAppsBean[0].reg_no\"]").click()
    page.locator("input[name=\"businessRegInfoAppsBean[0].reg_no\"]").press("CapsLock")
    page.locator("input[name=\"businessRegInfoAppsBean[0].reg_no\"]").fill("r")
    page.locator("input[name=\"businessRegInfoAppsBean[0].reg_no\"]").press("CapsLock")
    page.locator("input[name=\"businessRegInfoAppsBean[0].reg_no\"]").fill("REG-2025-001")
    page.get_by_role("textbox", name="Sec Primary Purpose").click()
    page.get_by_role("textbox", name="Sec Primary Purpose").press("CapsLock")
    page.get_by_role("textbox", name="Sec Primary Purpose").fill("Sec")
    page.get_by_role("textbox", name="Sec Primary Purpose").press("CapsLock")
    page.get_by_role("textbox", name="Sec Primary Purpose").fill("SEC PRIMARY PURPOSE 00")
    page.get_by_role("textbox", name="Authorized Amount (PHP)").click()
    page.get_by_role("textbox", name="Authorized Amount (PHP)").fill("100000000000000000")
    page.get_by_role("textbox", name="Authorized Amount (PHP)").press("Tab")
    page.get_by_role("textbox", name="Authorized Amount (PHP)").click()
    page.get_by_role("textbox", name="Authorized Amount (PHP)").fill("100,000,00,000.00")
    page.locator("#form_application").click()
    page.locator("#existing-business-registration").get_by_text("Previous Save and Proceed").click()
    page.get_by_role("textbox", name="Subscribe Amount (PHP)").click()
    page.get_by_role("textbox", name="Subscribe Amount (PHP)").fill("1,000,000,0000")
    page.get_by_role("textbox", name="Subscribe Amount (PHP)").press("Tab")
    page.get_by_role("textbox", name="* Paid-up Amount (PHP):").fill("1,000,000,0000")
    page.get_by_role("button", name="Save and Proceed").click()
    page.get_by_role("radio", name="Person").check()
    page.get_by_role("radio", name="Person").check()
    page.locator("#stockholderWrapper div").filter(has_text="Not Applicable").nth(1).click()
    page.get_by_role("button", name="Save and Proceed").click()
    page.get_by_role("button", name="Stockholders & Principal Officers").click()
    page.locator("#dt_principalOfficers_wrapper").click()
    page.get_by_title("Add Principal Officer").click()
    page.get_by_role("combobox", name="Select Salutation").locator("span").nth(1).click()
    page.get_by_role("option", name="Mr.").click()
    page.get_by_role("textbox", name="* First Name").click()
    page.get_by_role("textbox", name="* First Name").press("CapsLock")
    page.get_by_role("textbox", name="* First Name").fill("Pri")
    page.get_by_role("textbox", name="* First Name").press("CapsLock")
    page.get_by_role("textbox", name="* First Name").fill("PRNCIPAL FNAME")
    page.get_by_role("textbox", name="* First Name").press("Tab")
    page.get_by_role("textbox", name="Middle Name (Optional)").press("Tab")
    page.get_by_role("textbox", name="* Last Name").fill("PRINCIPAL LNAME")
    page.get_by_role("button", name=" Add").click()
    page.get_by_role("textbox", name="This field is required.").click()
    page.get_by_role("textbox", name="This field is required.").fill("PRESIDENT")
    page.get_by_role("button", name=" Add").click()
    page.get_by_role("button", name="Save and Proceed").click()
    page.locator(".form-control.bottom-border.ignore-form-submit.datepicker.timetable-dtpckr.year-month-picker.text-center.input").first.click()
    page.locator(".flatpickr-monthSelect-months > span:nth-child(12)").first.click()
    page.locator("div:nth-child(2) > .form-control.bottom-border.ignore-form-submit.datepicker.timetable-dtpckr.year-month-picker.text-center.input").first.click()
    page.locator(".flatpickr-calendar.animate.flatpickr-monthSelect-theme-light.open > .flatpickr-innerContainer > .flatpickr-rContainer > .flatpickr-monthSelect-months > span:nth-child(12)").click()
    page.locator("div:nth-child(2) > .form-control.bottom-border.ignore-form-submit.datepicker.timetable-dtpckr.year-month-picker.text-center.input").first.click()
    page.locator(".flatpickr-calendar.animate.flatpickr-monthSelect-theme-light.open > .flatpickr-months > .flatpickr-next-month > svg").click()
    page.get_by_label("December 1, 2027").click()
    page.locator("div:nth-child(2) > .card > .card-body > .row > div > .form-control.bottom-border.ignore-form-submit.datepicker.timetable-dtpckr.year-month-picker.text-center.input").first.click()
    page.locator(".flatpickr-calendar.animate.flatpickr-monthSelect-theme-light.open > .flatpickr-innerContainer > .flatpickr-rContainer > .flatpickr-monthSelect-months > span:nth-child(12)").click()
    page.locator("div:nth-child(2) > .card > .card-body > .row > div:nth-child(2) > .form-control.bottom-border.ignore-form-submit.datepicker.timetable-dtpckr.year-month-picker.text-center.input").first.click()
    page.locator(".flatpickr-calendar.animate.flatpickr-monthSelect-theme-light.open > .flatpickr-months > .flatpickr-next-month").click()
    page.get_by_label("December 1, 2027").first.click()
    page.locator(".card.mt-5 > .card-body > .row > div > .form-control.bottom-border.ignore-form-submit.datepicker.timetable-dtpckr.year-month-picker.text-center.input").first.click()
    page.locator(".flatpickr-calendar.animate.flatpickr-monthSelect-theme-light.open > .flatpickr-innerContainer > .flatpickr-rContainer > .flatpickr-monthSelect-months > span:nth-child(12)").click()
    page.locator(".card.mt-5 > .card-body > .row > div:nth-child(2) > .form-control.bottom-border.ignore-form-submit.datepicker.timetable-dtpckr.year-month-picker.text-center.input").first.click()
    page.locator(".flatpickr-calendar.animate.flatpickr-monthSelect-theme-light.open > .flatpickr-months > .flatpickr-next-month > svg").click()
    page.locator(".flatpickr-calendar.animate.flatpickr-monthSelect-theme-light.open > .flatpickr-innerContainer > .flatpickr-rContainer").click()
    page.locator("div:nth-child(2) > div:nth-child(2) > .card > .card-body > .row > div > .form-control.bottom-border.ignore-form-submit.datepicker.timetable-dtpckr.year-month-picker.text-center.input").first.click()
    page.locator(".flatpickr-calendar.animate.flatpickr-monthSelect-theme-light.open > .flatpickr-innerContainer > .flatpickr-rContainer > .flatpickr-monthSelect-months > span:nth-child(12)").click()
    page.locator("div:nth-child(2) > div:nth-child(2) > .card > .card-body > .row > div:nth-child(2) > .form-control.bottom-border.ignore-form-submit.datepicker.timetable-dtpckr.year-month-picker.text-center.input").click()
    page.locator(".flatpickr-calendar.animate.flatpickr-monthSelect-theme-light.open > .flatpickr-months > .flatpickr-next-month").click()
    page.get_by_label("December 1, 2027").first.click()
    page.locator(".col-sm-12 > .form-control.bottom-border.ignore-form-submit.datepicker.timetable-dtpckr.year-month-picker.text-center.input").click()
    page.locator(".flatpickr-calendar.animate.flatpickr-monthSelect-theme-light.open > .flatpickr-innerContainer > .flatpickr-rContainer > .flatpickr-monthSelect-months > span:nth-child(12)").click()
    page.locator(".col-sm-12 > .form-control.bottom-border.ignore-form-submit.datepicker.timetable-dtpckr.year-month-picker.text-center.input").click()
    page.locator(".flatpickr-calendar.animate.flatpickr-monthSelect-theme-light.open > .flatpickr-months > .flatpickr-next-month").click()
    page.locator(".flatpickr-calendar.animate.flatpickr-monthSelect-theme-light.open > .flatpickr-months > .flatpickr-next-month").click()
    page.get_by_label("January 1, 2028").click()
    page.locator("#servicePersonnelCount0").click()
    page.locator("#servicePersonnelCount0").fill("1")
    page.locator("#servicePersonnelCount1").click()
    page.locator("#servicePersonnelCount1").fill("10")
    page.get_by_role("cell", name="6").click()
    page.locator("#servicePersonnelCount2").click()
    page.locator("#servicePersonnelCount2").fill("100")
    page.locator("#indirectPersonnelCount0").click()
    page.locator("#indirectPersonnelCount0").fill("1")
    page.locator("#indirectPersonnelCount1").click()
    page.locator("#indirectPersonnelCount1").fill("10")
    page.locator("#indirectPersonnelCount2").click()
    page.locator("#indirectPersonnelCount2").fill("1,00")
    page.locator("#adminPersonnelCount0").click()
    page.locator("#adminPersonnelCount0").fill("1")
    page.locator("#adminPersonnelCount1").click()
    page.locator("#adminPersonnelCount1").fill("10")
    page.locator("#adminPersonnelCount2").click()
    page.locator("#adminPersonnelCount2").fill("100")
    page.get_by_role("button", name="Save and Proceed").click()
    page.get_by_role("textbox", name="Describe the Manufacturing").click()
    page.get_by_role("textbox", name="Describe the Manufacturing").press("CapsLock")
    page.get_by_role("textbox", name="Describe the Manufacturing").fill("Ma")
    page.get_by_role("textbox", name="Describe the Manufacturing").press("CapsLock")
    page.get_by_role("textbox", name="Describe the Manufacturing").fill("MANUFACTURING PROCESS SERVICE FLOW TESTING 001")
    page.locator("#addtlInfo_supporting_documentsDropzone").get_by_text("Upload File Drag files here").click()
    page.get_by_text("Loading... Dashboard Permit").set_input_files("Testing_document.png")
    page.get_by_role("button", name="Save and Proceed").click()
    page.locator("#machineryEquipmentTotalQuantity").click()
    page.locator("#machineryEquipmentTotalQuantity").click()
    page.locator("#dt_machineryEquipment").get_by_role("cell", name="No data available in table").click()
    page.locator("#dt_machineryEquipment").get_by_role("cell", name="No data available in table").click()
    page.locator("#machineryEquipmentTotalQuantity").click()
    page.locator("#machineryEquipmentTotalQuantity").click()
    page.locator("#machineryEquipmentTotalQuantity").click()
    page.locator("#machineryEquipmentTotalUnitCost").click()
    page.get_by_title("Machinery/Equipments").click()
    page.get_by_role("textbox", name="* Item Description").click()
    page.get_by_role("textbox", name="* Item Description").press("CapsLock")
    page.get_by_role("textbox", name="* Item Description").fill("Desri")
    page.get_by_role("textbox", name="* Item Description").press("CapsLock")
    page.get_by_role("textbox", name="* Item Description").fill("DESCRIPTION 001")
    page.get_by_role("textbox", name="* Item Description").press("Tab")
    page.locator("#itemQty").fill("100")
    page.locator("#itemQty").press("Tab")
    page.locator("#itemUnitCost").fill("1000")
    page.get_by_role("textbox", name="Select Source").click()
    page.get_by_role("option", name="IMPORTED").click()
    page.get_by_text("* Item Description * Quantity * Unit Cost (PHP) * Source Select Source IMPORTED").click()
    page.get_by_role("textbox", name="Select Country").click()
    page.get_by_role("searchbox").fill("GER")
    page.get_by_role("option", name="[DE] Germany").click()
    page.get_by_role("button", name=" Save & Add New").click()
    page.get_by_role("button", name="Close").click()
    page.get_by_title("Raw Material/Semi Finished").click()
    page.get_by_role("textbox", name="* Item Description").click()
    page.get_by_role("textbox", name="* Item Description").fill("ITEM DESCRIPTION 001")
    page.get_by_role("textbox", name="Select Source").click()
    page.get_by_role("option", name="IMPORTED").click()
    page.get_by_role("textbox", name="Select Country").click()
    page.get_by_role("searchbox").fill("GE")
    page.get_by_role("searchbox").click()
    page.get_by_role("searchbox").fill("GERMA")
    page.get_by_role("option", name="[DE] Germany").click()
    page.get_by_role("button", name=" Add").click()
    page.get_by_role("cell").filter(has_text=re.compile(r"^$")).nth(4).click()
    page.locator("#prodSchedShifts0").click()
    page.locator("#prodSchedShifts0").fill("3")
    page.locator("#prodSchedShifts0").press("Tab")
    page.locator("#prodSchedHourShifts0").fill("8")
    page.locator("#prodSchedHourShifts0").press("Tab")
    page.locator("#prodSchedDaysMonth0").fill("21")
    page.get_by_role("button", name="Save and Proceed").click()
    page.locator("#total_area_sqm").click()
    page.locator("#total_area_sqm").fill("100")
    page.get_by_role("textbox", name="Select Zone").click()
    page.get_by_role("option", name="[2CYV] [24]7 PLAZA").click()
    page.get_by_role("textbox", name="Select Region").click()
    page.get_by_role("option", name="NATIONAL CAPITAL REGION (NCR)").click()
    page.get_by_role("textbox", name="Select Province").click()
    page.get_by_role("option", name="METRO MANILA").click()
    page.locator("#area-disposable-waste-disposal div").filter(has_text="* STREET NAME:").nth(3).click()
    page.get_by_role("textbox", name="Select City/Municipality").click()
    page.get_by_role("option", name="CALOOCAN CITY").click()
    page.get_by_role("textbox", name="Select Barangay").click()
    page.get_by_role("option", name="BARANGAY 1", exact=True).click()
    page.get_by_role("textbox", name="Street Name").click()
    page.get_by_role("textbox", name="Street Name").press("CapsLock")
    page.get_by_role("textbox", name="Street Name").fill("Street name")
    page.get_by_role("textbox", name="Street Name").press("CapsLock")
    page.get_by_role("textbox", name="Street Name").fill("STREET NAME")
    page.locator("#unitOwnerFirstname").click()
    page.locator("#unitOwnerFirstname").fill("OWNER OF LOT")
    page.locator("#unitOwnerFirstname").press("Tab")
    page.locator("#unitOwnerMiddlename").press("Tab")
    page.locator("#unitOwnerLastname").press("Tab")
    page.locator("#unitOwnerFirstname").click()
    page.locator("#unitOwnerFirstname").press("ArrowRight")
    page.locator("#unitOwnerFirstname").press("ArrowRight")
    page.locator("#unitOwnerFirstname").press("ArrowRight")
    page.locator("#unitOwnerFirstname").press("ArrowRight")
    page.locator("#unitOwnerFirstname").fill("OWNER FNAME")
    page.locator("#unitOwnerLastname").click()
    page.locator("#unitOwnerLastname").fill("OWNER LANME")
    page.locator("#lotOwnerFirstname").click()
    page.locator("#lotOwnerFirstname").fill("LOT FNAME")
    page.locator("#lotOwnerFirstname").press("Tab")
    page.locator("#lotOwnerLastname").fill("LOT LNAME")
    page.locator("#lessorFirstname").click()
    page.locator("#lessorFirstname").fill("LESSOR FNAME")
    page.locator("#lessorFirstname").press("Tab")
    page.locator("#lessorLastname").fill("LESSOR LNAME")
    page.locator("#water_yr_req").click()
    page.locator("#water_yr_req").fill("500")
    page.locator("#water_yr_req").press("Tab")
    page.locator("#electric_yr_req").fill("10,0000")
    page.locator("#waste_disposal_desc").click()
    page.locator("#waste_disposal_desc").fill("WASTE DISPOSAL")
    page.locator("#waste_disposal_desc").press("Tab")
    page.locator("#waste_disposal_method_desc").fill("DISCUSSION OF METHODS")
    page.locator("#activity_wasteproducts_supporting_documentsDropzone").get_by_role("link", name="Click Here").click()
    page.locator("#activity_wasteproducts_supporting_documentsDropzone").get_by_role("link", name="Click Here").set_input_files("Testing_document.png")
    page.locator("#activity_generatedwaste_supporting_documentsDropzone").get_by_text("Drag files here to upload").click()
    page.get_by_text("Loading... Dashboard Permit").set_input_files("Testing_document.png")
    page.get_by_role("button", name="Save and Proceed").click()
    page.locator("#select2-exportPercent-container").click()
    page.get_by_role("heading", name="* Market Aspect").click()
    page.get_by_role("list").filter(has_text=re.compile(r"^$")).click()
    page.get_by_role("searchbox").fill("GER")
    page.get_by_role("option", name="[DE] Germany").click()
    page.locator("tags").get_by_role("textbox").click()
    page.locator("tags").get_by_role("textbox").fill("DOMESTIC CLIENTS")
    page.locator("tags").get_by_role("textbox").press("Tab")
    page.locator("tags").get_by_role("textbox").click()
    page.locator("tags").get_by_role("textbox").fill("CLEINTS DOMESTICS")
    page.locator("tags").get_by_role("textbox").press("Tab")
    page.get_by_role("textbox", name="Amount (to the nearest dollar)").click()
    page.get_by_role("textbox", name="Amount (to the nearest dollar)").fill("100,00")
    page.get_by_role("textbox", name="Amount (to the nearest dollar)").press("Tab")
    page.get_by_role("textbox", name="Amount (to the nearest peso)").click()
    page.get_by_role("textbox", name="Amount (to the nearest peso)").fill("50,00")
    page.locator("#market-aspect div").filter(has_text="* Unit of Measure: Select UOM").nth(2).click()
    page.get_by_role("textbox", name="Select UOM").click()
    page.get_by_role("searchbox").nth(1).fill("KILO")
    page.get_by_role("option", name="[KGM] Kilogram").click()
    page.get_by_title("Add Export").click()
    page.locator("#export_marketAspectVolumeValue0").click()
    page.locator("#export_marketAspectVolumeValue0").fill("1000")
    page.get_by_title("Add Local").click()
    page.locator("#import_marketAspectVolumeValue0").click()
    page.locator("#import_marketAspectVolumeValue0").fill("1000")
    page.locator("#berms-application div").filter(has_text="* Application Fill up all the").nth(1).click()
    page.get_by_role("button", name="Save and Proceed").click()
    page.get_by_role("row", name="* Building Construction/").get_by_role("cell").nth(1).click()
    page.get_by_role("row", name="* Building Construction/").get_by_placeholder("0").fill("1,0000")
    page.get_by_role("row", name="* Building Construction/").get_by_placeholder("0").press("Tab")
    page.get_by_role("row", name="* Building Construction/").get_by_label("Not Applicable").press("Tab")
    page.get_by_role("row", name="* Factory Tools 0 Not").get_by_placeholder("0").fill("1000")
    page.get_by_role("row", name="* Factory Tools 0 Not").get_by_placeholder("0").press("Tab")
    page.get_by_role("row", name="* Building Construction/").get_by_role("cell").nth(1).click()
    page.get_by_role("cell", name="10,000.00").get_by_placeholder("0").fill("10,000.00")
    page.get_by_role("row", name="* Building Construction/").get_by_role("cell").nth(1).dblclick()
    page.get_by_role("row", name="* Transportation 0.00 Not").get_by_placeholder("0").click()
    page.get_by_role("row", name="* Transportation 0.00 Not").get_by_placeholder("0").dblclick()
    page.get_by_role("row", name="* Transportation 0.00 Not").get_by_placeholder("0").fill("1000")
    page.get_by_role("row", name="* Transportation 0.00 Not").get_by_placeholder("0").press("Tab")
    page.get_by_role("row", name="* Office Furniture, Fixtures").get_by_placeholder("0").fill("10,00")
    page.get_by_role("row", name="* Office Furniture, Fixtures").get_by_label("Not Applicable").press("Tab")
    page.get_by_role("row", name="Other Assets").get_by_placeholder("0").fill("1000")
    page.get_by_role("row", name="Other Assets").get_by_placeholder("0").press("Tab")
    page.get_by_role("textbox", name="specify").press("Tab")
    page.get_by_role("row", name="* Pre-operating Expenses 0").get_by_placeholder("0").fill("1000")
    page.get_by_role("row", name="* Pre-operating Expenses 0").get_by_placeholder("0").press("Tab")
    page.get_by_role("row", name="* Working Capital (one").get_by_placeholder("0").fill("1000")
    page.get_by_role("row", name="Equity ").get_by_placeholder("0").click()
    page.get_by_role("row", name="Equity ").get_by_placeholder("0").fill("1000")
    page.get_by_role("row", name="Equity ").get_by_placeholder("0").press("Tab")
    page.get_by_role("row", name="Equity ").get_by_placeholder("0").click()
    page.get_by_role("row", name="Equity ").get_by_placeholder("0").fill("1,00.00")
    page.get_by_role("row", name="Equity ").get_by_placeholder("0").press("Tab")
    page.get_by_role("row", name="Additional Equity").get_by_placeholder("0").fill("100")
    page.get_by_role("row", name="Additional Equity").get_by_placeholder("0").press("Tab")
    page.get_by_role("row", name="Advances Select Loan Type").get_by_placeholder("0").fill("100")
    page.get_by_role("row", name="Advances Select Loan Type").get_by_placeholder("0").press("Tab")
    page.get_by_role("row", name="Loans Select Loan Type").get_by_placeholder("0").fill("100")
    page.locator("#fundSource2").select_option("FOREIGN_LOAN")
    page.locator("#fundSource3").select_option("LOCAL_LOAN")
    page.get_by_role("button", name="Save and Proceed").click()
    page.locator("#dropzoneInnersc_agraft9").get_by_text("CHOOSE FILE TO UPLOAD or drag").click()
    page.get_by_text("Loading... Dashboard Permit").set_input_files("Testing_document.png")
    page.locator("#dropzoneInnerund8").get_by_text("CHOOSE FILE TO UPLOAD or drag").click()
    page.get_by_text("Loading... Dashboard Permit").set_input_files("viber_image_2023-12-22_11-17-40-619.png")
    page.locator("#dropzoneInnerby_law7").get_by_text("CHOOSE FILE TO UPLOAD or drag and drop them here FILE READY TOUPLOAD").click()
    page.get_by_text("Loading... Dashboard Permit").set_input_files("Testing_document.png")
    page.locator("#dropzoneInneraoi6").get_by_text("CHOOSE FILE TO UPLOAD or drag and drop them here FILE READY TOUPLOAD").click()
    page.get_by_text("Loading... Dashboard Permit").set_input_files("Testing_document.png")
    page.locator("#dropzoneInnergis5").get_by_text("CHOOSE FILE TO UPLOAD or drag").click()
    page.get_by_text("Loading... Dashboard Permit").set_input_files("Testing_document.png")
    page.locator("#dropzoneInnerpfs4").get_by_text("CHOOSE FILE TO UPLOAD or drag").click()
    page.get_by_text("Loading... Dashboard Permit").set_input_files("FOR UPLOADING MOE- STAGGING.xlsx")
    page.locator("#dropzoneInnerbir3").get_by_text("CHOOSE FILE TO UPLOAD or drag").click()
    page.get_by_text("Loading... Dashboard Permit").set_input_files("Testing_document.png")
    page.locator("#dropzoneInnercppc2").get_by_text("or drag and drop them here").click()
    page.get_by_text("Loading... Dashboard Permit").set_input_files("Testing_document.png")
    page.locator("#dropzoneInnerrbpo1").get_by_text("CHOOSE FILE TO UPLOAD").click()
    page.get_by_text("Loading... Dashboard Permit").set_input_files("Testing_document.png")
    page.locator("#dropzoneInnercrsec0").get_by_text("CHOOSE FILE TO UPLOAD or drag").click()
    page.get_by_text("Loading... Dashboard Permit").set_input_files("Testing_document.png")
    page.get_by_role("button", name="Save and Proceed").click()
    expect(page.get_by_role("button", name="Confirmation")).to_be_visible()
    page.get_by_role("button", name="Submit").click()
    page.get_by_role("button", name="OK").click()
    page.get_by_role("button", name="Market Aspect").click()
    page.get_by_title("Add Export").click()
    page.locator("#export_marketAspectVolumeValue1").click()
    page.locator("#export_marketAspectVolumeValue1").fill("1000")
    page.get_by_title("Add Export").click()
    page.locator("#dt-market-asp-export_wrapper > .dt-action-buttons").first.click()
    page.locator("#dt-market-asp-export_wrapper > .dt-action-buttons").first.click()
    page.locator("#export_marketAspectVolumeValue2").click()
    page.locator("#export_marketAspectVolumeValue2").click()
    page.locator("#export_marketAspectVolumeValue2").fill("1000")
    page.get_by_title("Add Local").click()
    page.locator("#import_marketAspectVolumeValue1").click()
    page.locator("#import_marketAspectVolumeValue1").click()
    page.locator("#import_marketAspectVolumeValue1").fill("100")
    page.get_by_role("cell", name="100").get_by_placeholder("0.00").fill("0100")
    page.get_by_title("Add Local").click()
    page.locator("#import_marketAspectVolumeValue2").click()
    page.locator("#import_marketAspectVolumeValue2").fill("100")
    page.get_by_role("button", name="Save and Proceed").click()
    page.get_by_role("textbox", name="This field is required.").click()
    page.get_by_role("textbox", name="This field is required.").click()
    page.get_by_role("textbox", name="This field is required.").fill("POWER STONE")
    page.get_by_role("row", name="Advances Foreign Loan").get_by_placeholder("0").click()
    page.get_by_role("row", name="Additional Equity").get_by_placeholder("0").click()
    page.get_by_role("row", name="Additional Equity").get_by_placeholder("0").fill("1,100.00")
    page.get_by_role("row", name="Additional Equity").get_by_placeholder("0").press("ArrowLeft")
    page.get_by_role("row", name="Additional Equity").get_by_placeholder("0").press("ArrowLeft")
    page.get_by_role("row", name="Additional Equity").get_by_placeholder("0").press("ArrowRight")
    page.get_by_role("row", name="Additional Equity").get_by_placeholder("0").fill(",100.00")
    page.get_by_role("row", name="Advances Foreign Loan").get_by_placeholder("0").click()
    page.get_by_role("row", name="Advances Foreign Loan").get_by_placeholder("0").fill("1000.00")
    page.get_by_role("row", name="Advances Foreign Loan").get_by_placeholder("0").press("ArrowLeft")
    page.get_by_role("row", name="Advances Foreign Loan").get_by_placeholder("0").press("ArrowLeft")
    page.get_by_role("row", name="Advances Foreign Loan").get_by_placeholder("0").fill("1,0000.00")
    page.get_by_role("row", name="Advances Foreign Loan").get_by_placeholder("0").press("ArrowLeft")
    page.get_by_role("row", name="Advances Foreign Loan").get_by_placeholder("0").press("ArrowLeft")
    page.get_by_role("row", name="Advances Foreign Loan").get_by_placeholder("0").fill("10,0000.00")
    page.get_by_role("row", name="Loans Local Loan").get_by_placeholder("0").click()
    page.get_by_role("row", name="Loans Local Loan").get_by_placeholder("0").fill("1100.00")
    page.get_by_role("row", name="Loans Local Loan").get_by_placeholder("0").click()
    page.get_by_role("row", name="Loans Local Loan").get_by_placeholder("0").fill("1100.00")
    page.get_by_role("row", name="Loans Local Loan").get_by_placeholder("0").click()
    page.get_by_role("row", name="Loans Local Loan").get_by_placeholder("0").press("ArrowLeft")
    page.get_by_role("row", name="Loans Local Loan").get_by_placeholder("0").press("ArrowRight")
    page.get_by_role("row", name="Loans Local Loan").get_by_placeholder("0").press("ArrowRight")
    page.get_by_role("row", name="Loans Local Loan").get_by_placeholder("0").press("ArrowLeft")
    page.get_by_role("row", name="Loans Local Loan").get_by_placeholder("0").fill("1100.00")
    page.get_by_role("row", name="Loans Local Loan").get_by_placeholder("0").press("ArrowLeft")
    page.get_by_role("row", name="Loans Local Loan").get_by_placeholder("0").press("ArrowLeft")
    page.get_by_role("row", name="Loans Local Loan").get_by_placeholder("0").press("ArrowLeft")
    page.get_by_role("row", name="Loans Local Loan").get_by_placeholder("0").press("ArrowRight")
    page.get_by_role("row", name="Loans Local Loan").get_by_placeholder("0").press("ArrowRight")
    page.get_by_role("row", name="Loans Local Loan").get_by_placeholder("0").fill("9000")
    page.get_by_role("row", name="Additional Equity").get_by_placeholder("0").click()
    page.get_by_role("row", name="Additional Equity").get_by_placeholder("0").fill("1000")
    page.get_by_role("row", name="Equity ").get_by_placeholder("0").dblclick()
    page.get_by_role("row", name="Equity ").get_by_placeholder("0").fill("6000")
    page.locator("#project-cost-and-source-of-financing #sofErrorMsg").get_by_text("Total Initial Project Cost").click()
    page.get_by_role("button", name="Save and Proceed").click()
    page.get_by_role("button", name="Market Aspect").click()
    page.get_by_role("button", name="Stockholders & Principal Officers").click()
    page.get_by_role("radio", name="Not Applicable Not Applicable").check()
    page.get_by_role("radio", name="Person Person").check()
    page.get_by_role("button", name="Save and Proceed").click()
    page.get_by_role("button", name="Confirmation").click()
    page.get_by_role("button", name="Submit").click()
    page.get_by_role("dialog", name="Unable to process request").click()
    page.get_by_role("button", name="OK").click()
    page.get_by_role("button", name="Stockholders & Principal Officers").click()
    page.get_by_role("radio", name="Not Applicable Not Applicable").check()
    page.locator("#stockholders-and-principles").click()
    page.get_by_title("Add Stockholder").click()
    page.locator("#proposedStockholderFirstName").click()
    page.locator("#proposedStockholderFirstName").fill("ST FNAME")
    page.locator("#proposedStockholderFirstName").press("Tab")
    page.locator("#proposedStockholderMiddleName").press("Tab")
    page.locator("#proposedStockholderLastName").fill("ST LNAME")
    page.locator("#proposedStockholderLastName").press("Tab")
    page.get_by_role("textbox", name="Select Suffix").click()
    page.locator(".select2-search.select2-search--dropdown").click()
    page.get_by_role("textbox", name="No. of Shares *").click()
    page.get_by_role("textbox", name="No. of Shares *").fill("100")
    page.get_by_role("textbox", name="No. of Shares *").press("Tab")
    page.get_by_role("textbox", name="Amount Subscribe (PHP) *").fill("1,000,000,0000")
    page.get_by_role("textbox", name="Amount Paid-up (PHP) *").click()
    page.get_by_role("textbox", name="Amount Paid-up (PHP) *").fill("1,000,000,0000")
    page.get_by_role("button", name=" Add").click()
    page.get_by_role("textbox", name="Select Salutation").click()
    page.get_by_role("option", name="Mr.").click()
    page.get_by_role("button", name=" Add").click()
    page.get_by_role("button", name="Save and Proceed").click()
    page.get_by_role("button", name="Confirmation").click()
    page.get_by_role("button", name="Submit").click()
    page.get_by_role("button", name="Proceed").click()
    page.get_by_role("button", name="OK").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)